### PR TITLE
fix: #104 - outdated SDK version

### PR DESCRIPTION
**Pull request by sbaeurle**
As described in #104, the current `azure-devops-extension-sdk` used in this package is outdated and creates problems due to the global version check, that ensures only one SDK instance to be present.

This PR addresses this issue, by updating the corresponding dependency.

Beware, NPM changed the lock file version to `2` automatically!

### CODE REVIEW

**Comment by sbaeurle** [comment]
@microsoft-github-policy-service agree company="Harro Höfliger"

**Review by karelkral — APPROVED** [review]

**Comment by sbaeurle** [comment]
@karekal
Thanks for the review, however it seems someone with more privilege is missing :)

**Comment by sbaeurle** [comment]
Any update regarding another reviewer? :)

**Comment by 50Wliu** [comment]
Hmm. I should have looked through the existing PRs first. I just created #110 which is a different way of tackling the same issue. I explicitly chose marking it as a peer dependency rather than updating the dependency itself - this is my first time actually dealing with peer deps first hand, so if you have any thoughts I'd love to hear them!

**Comment by sbaeurle** [comment]
The question is, whether you'll need the sdk for compiling the api sources.
If not, I guess marking it as peer dependency seems fine for me.
This way, one would leave more control to the user (not sure if different major versions of the sdk are required for different DevOps versions)

**Comment by sbaeurle** [comment]
Fixed by #111

**Pull request closed without merging**
